### ISSUE TITLE
Error with installer / service

### ISSUE THREAD

**Issue by ghost** [svenkle/nuget-server#1]
I downloaded and ran the installer.msi file (no errors), bud didn't see a Windows service added. I opened a command prompt and ran the main exe and got this output:

```
C:\Program Files (x86)\Svenkle\NuGet Server>Svenkle.NuGetServer.Service.exe
[Svenkle.NuGetServer.Service]
Starting...
System.IO.IOException: Could not complete operation on some files and directories. See the Data property of the exception for more details.
   at Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryName, String destinationDirectoryName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Svenkle.NuGetServer.Service.Service.ExtractHost()
   at Svenkle.NuGetServer.Service.Service.OnStart(String[] args)
   at Svenkle.NuGetServer.Service.Service.Main(String[] args)

Unhandled Exception: System.IO.IOException: Could not complete operation on some files and directories. See the Data property of the exception for more details.
   at Microsoft.VisualBasic.FileIO.FileSystem.FxCopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryPath, String targetDirectoryPath, Boolean overwrite)
   at Microsoft.VisualBasic.FileIO.FileSystem.CopyOrMoveDirectory(CopyOrMove operation, String sourceDirectoryName, String destinationDirectoryName, Boolean overwrite, UIOptionInternal showUI, UICancelOption onUserCancel)
   at Svenkle.NuGetServer.Service.Service.ExtractHost()
   at Svenkle.NuGetServer.Service.Service.OnStart(String[] args)
   at Svenkle.NuGetServer.Service.Service.Main(String[] args)

C:\Program Files (x86)\Svenkle\NuGet Server>
```

**Comment by ghost** [comment]
The error appears to be related to permissions, but still curious why the installer didn't install a Windows service. Or am I misunderstanding what the installer is performing?

**Comment by svenkle** [comment]
@shanewalters the error is from the IIS Express extraction process as it must have write permissions to the temporary folders (maybe try running as Administrator).

As for the Installer.msi - have you tried restarting your machine? I've found that when using the Installer wrapper application (aip) any services added will not show in the list until next system restart.

**Comment by svenkle** [comment]
I'm going to go ahead and close this as you haven't replied.
